apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-opex-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: kube-opex-storage
  hostPath:
    path: "/data/db"
  persistentVolumeReclaimPolicy: Retain
