apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: spark-storage
  hostPath:
    path: "/home/ubuntu/data/spark"
  persistentVolumeReclaimPolicy: Retain
