version: "3.3"
services:
#AWS CloudFormation Stack creator
  stack:
    image: ilyassifez/bdataprojectpython:stacky
    container_name: stack
    volumes:
      - mykubeconfig:/root/.kube
      - myawsconfig:/root/.aws
    network_mode: "host"
    command: ["python3.8","main.py 0"]
    environment:
      ACCESS_KEY: $ACCESS_KEY
      SECRET_KEY: $SECRET_KEY
      REGION: $REGION
#Volumes
volumes:
  mykubeconfig: {}
  myawsconfig: {}
